INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

# Evaluation datasets
GRABCUT_PATH: "./datasets/GrabCut"
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH: "./datasets/DAVIS"
COCO_MVAL_PATH: "./datasets/COCO_MVal"
AVALANCHE_PATH_1: "./datasets/Avalanche_1/"
AVALANCHE_PATH_2: "./datasets/Avalanche_2/"
AVALANCHE_PATH_3: "./datasets/Avalanche_3/"
AVALANCHE_PATH_4: "./datasets/Avalanche_3a/"
AVALANCHE_PATH_5: "./datasets/Avalanche_3b/"
AVALANCHE_PATH_6: "./datasets/Avalanche_4/" # avalanche 4 contains train and vali photos
AVALANCHE_PATH_7: "./datasets/Avalanches_train/" # avalanche_train contains cropped train photos
AVALANCHE_PATH_8: "./datasets/Avalanches_vali/" # avalanche_train contains cropped vali photos
AVALANCHE_PATH_9: "./datasets/Avalanche_DG/" # avalanche Dg contains pics from Börterhorn/ unknown cam-domain gap
AVALANCHE_PATH_10: "./datasets/Train_ours_uibk/" # contains the uibk train set together with ours
AVALANCHE_PATH_11: "./datasets/Vali_ours_uibk/" #  contains the uibk test set together with ours
AVALANCHE_PATH_12: "./datasets/Avalanche_uibk_test_all/" # contains the uibk test set
AVALANCHE_PATH_13: "./datasets/Avalanche_uibk_test_all1/" # contains the uibk test set without glide snow cracks
AVALANCHE_PATH_14: "./datasets/Vali_/" # contains the validation dataset from us and uibk
AVALANCHE_PATH_15: "./datasets/Avalanche_uibk_train/" # contains the uibk train set
AVALANCHE_PATH_16: "./datasets/Avalanches_uibk_vali1/" # contains uibk vali images wo glide cracks
AVALANCHE_PATH_17: "./datasets/U_study_data/" # contains the 20 User study images/masks
AVALANCHE_PATH_18: "./datasets/small_dataset/" # first small dataset for ortho + dsm
AVALANCHE_PATH_19: "./datasets/DS_v2_1m/" #dataset v2 with 1m resolution
AVALANCHE_PATH_20: "./datasets/DS_v2_0p5m/" #dataset v2 with 0.5m resolution
AVALANCHE_PATH_21: "./datasets/DS_v2_0p5m_test/" #dataset v2 with 0.5m resolution
AVALANCHE_PATH_22: "./datasets/DS_v2_0p1m/" #dataset v2 with 0.1m resolution
AVALANCHE_PATH_23: "./datasets/DS_v2_0p1m_test/" #dataset v2 with 0.1m resolution
AVALANCHE_PATH_24: "./datasets/DS_v2_1m_test/" #dataset v2 with 1m resolution
AVALANCHE_PATH_25: "./datasets/DS_v3_0p2m_train/"
AVALANCHE_PATH_26: "./datasets/DS_v3_0p2m_test/"
AVALANCHE_PATH_27: "./datasets/DS_v3_0p5m_train/"
AVALANCHE_PATH_28: "./datasets/DS_v3_0p5m_test/"
AVALANCHE_PATH_29: "./datasets/DS_v3_1m_train/"
AVALANCHE_PATH_30: "./datasets/DS_v3_1m_test/"
AVALANCHE_PATH_31: "./datasets/DS_v3_2m_train/"
AVALANCHE_PATH_32: "./datasets/DS_v3_2m_test/"
AVALANCHE_PATH_33: "./datasets/DS_v3_5m_train/"
AVALANCHE_PATH_34: "./datasets/DS_v3_5m_test/"
AVALANCHE_PATH_35: "./datasets/ds_v3_0p5m_gB_sig0p5_test/"
AVALANCHE_PATH_35: "./datasets/ds_v3_0p5m_gB_sig1_test/"
AVALANCHE_PATH_35: "./datasets/ds_v3_0p5m_gB_sig2p5_test/"
AVALANCHE_PATH_35: "./datasets/ds_v3_0p5m_gB_sig5_test/"





# Train datasets
SBD_PATH: "./datasets/SBD"
COCO_PATH: "./datasets/coco2017"
LVIS_PATH: "./datasets/LVIS"
OPENIMAGES_PATH: "./datasets/OpenImages"
PASCALVOC_PATH: "./datasets/PascalVOC"
ADE20K_PATH: "./datasets/ADE20K"
AVALANCHE_TRAIN: "./datasets/Avalanches_train/"
AVALANCHE_VALI: "./datasets/Avalanches_vali/"
AVALANCHE_TRAIN_uibk: "./datasets/Avalanches_uibk_train/"
AVALANCHE_VALI_uibk: "./datasets/Avalanches_uibk_vali/"
AVALANCHE_TRAIN_uibk_woGcracks: "./datasets/Avalanches_uibk_train1/" # uibk data with glide snow cracks sorted out
AVALANCHE_VALI_uibk_woGcracks: "./datasets/Avalanches_uibk_vali1/" # uibk data with glide snow cracks sorted out
AVALANCHE_train_combo: "./datasets/Train_ours_uibk/" #combo of uibk without glide snow cracks and ours
AVALANCHE_test_combo: "./datasets/Vali_ours_uibk/" #combo of uibk without glide snow cracks and ours
DS_v2_1m: "./datasets/DS_v2_1m/" #dataset v2 with 1m resolution
DS_v2_1m_test: "./datasets/DS_v2_1m_test/" #dtest ataset v2 with 1m resolution
DS_v2_0p5m: "./datasets/DS_v2_0p5m/" #dataset v2 with 0.5m resolution
DS_v2_0p5m_test: "./datasets/DS_v2_0p5m_test/" #test dataset v2 with 0.5m resolution
DS_v2_0p1m: "./datasets/DS_v2_0p1m/" #dataset v2 with 0.1m resolution
DS_v2_0p1m_test: "./datasets/DS_v2_0p1m_test/" #test dataset v2 with 0.1m resolution

DS_v3_0p2m_train: "./datasets/DS_v3_0p2m_train/"
DS_v3_0p2m_test: "./datasets/DS_v3_0p2m_test/"
DS_v3_0p5m_train: "./datasets/DS_v3_0p5m_train/"
DS_v3_0p5m_test: "./datasets/DS_v3_0p5m_test/"
DS_v3_1m_train: "./datasets/DS_v3_1m_train/"
DS_v3_1m_test: "./datasets/DS_v3_1m_test/"
DS_v3_2m_train: "./datasets/DS_v3_2m_train/"
DS_v3_2m_test: "./datasets/DS_v3_2m_test/"
DS_v3_5m_train: "./datasets/DS_v3_5m_train/"
DS_v3_5m_test: "./datasets/DS_v3_5m_test/"
DS_v3_0p5m_gB_sig0p5_train: "./datasets/ds_v3_0p5m_gB_sig0p5_train"
DS_v3_0p5m_gB_sig1_train: "./datasets/ds_v3_0p5m_gB_sig1_train"
DS_v3_0p5m_gB_sig2p5_train: "./datasets/ds_v3_0p5m_gB_sig2p5_train"
DS_v3_0p5m_gB_sig5_train: "./datasets/ds_v3_0p5m_gB_sig5_train"



# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
  HRNETV2_W18_SMALL: "./pretrained_models/hrnet_w18_small_model_v2.pth"
